"""Reusable audio signal generation and analysis primitives."""

from .audioio import AudioDevice, list_devices, play_and_record
from .generators import (
    extend_log_sweep_band,
    log_chirp,
    periodic_pink_noise,
    pink_noise,
    pinking_sos,
    white_noise,
)
from .levels import as_channels, normalize_peak, peak_levels
from .impedance import (
    CHANNEL_CALIBRATION_DURATION,
    ChannelCalibration,
    ImpedanceConfig,
    ImpedanceResult,
    ReferenceCalibration,
    analyze_recording_levels,
    calculate_calibration_impedance,
    calculate_channel_correction,
    calculate_impedance,
    channel_calibration_config,
    current_phase_angle,
    estimate_reference_resistor,
    generate_channel_calibration_signal,
    generate_level_test_signal,
    generate_measurement_signal,
    interpolate_channel_calibration,
    require_valid_reference_calibration,
    trim_recording,
)
from .impedance_model import (
    FitResult,
    SpiceTableValues,
    fit_impedance,
    fit_impedance_auto,
    format_spice_table,
    speaker_impedance,
)
from .phase import (
    SPEED_OF_SOUND_M_S,
    PhaseConfig,
    PhaseResult,
    analyze_phase,
    break_phase_wraps,
    estimate_phase_delay,
    phase_derivative,
    wrap_phase,
)
from .rta import (
    RTAConfig,
    RTAResult,
    RTAWindow,
    analyze_rta,
    compensate_log_band_density,
)
from .smoothing import SmoothingWindow, grid_smooth, log_smooth, log_window
from .spectrum import (
    AnalysisMethod,
    ReferenceMode,
    SpectrumConfig,
    SpectrumResult,
    analyze_spectrum,
    calculate_power_spectrum,
    magnitude_db,
    phase_degrees,
    power_db,
    smooth_power_spectrum,
)
from .thd import (
    SemiAnalogTHDConfig,
    SemiAnalogTHDResult,
    THDResult,
    analyze_semi_analog_thd,
    fundamental_rejection_response,
    generate_semi_analog_thd_sweep,
    thd_from_spectrum,
)
from .types import ASignal, FrequencyBand

__all__ = [
    "AnalysisMethod",
    "AudioDevice",
    "ASignal",
    "FrequencyBand",
    "FitResult",
    "ImpedanceConfig",
    "ImpedanceResult",
    "PhaseConfig",
    "PhaseResult",
    "ReferenceMode",
    "RTAConfig",
    "RTAResult",
    "RTAWindow",
    "SmoothingWindow",
    "SpectrumConfig",
    "SpectrumResult",
    "SPEED_OF_SOUND_M_S",
    "SpiceTableValues",
    "SemiAnalogTHDConfig",
    "SemiAnalogTHDResult",
    "THDResult",
    "ChannelCalibration",
    "ReferenceCalibration",
    "CHANNEL_CALIBRATION_DURATION",
    "analyze_recording_levels",
    "analyze_semi_analog_thd",
    "analyze_phase",
    "analyze_rta",
    "compensate_log_band_density",
    "analyze_spectrum",
    "as_channels",
    "break_phase_wraps",
    "calculate_power_spectrum",
    "calculate_calibration_impedance",
    "calculate_channel_correction",
    "calculate_impedance",
    "channel_calibration_config",
    "current_phase_angle",
    "estimate_reference_resistor",
    "estimate_phase_delay",
    "extend_log_sweep_band",
    "fundamental_rejection_response",
    "fit_impedance",
    "fit_impedance_auto",
    "format_spice_table",
    "generate_channel_calibration_signal",
    "generate_level_test_signal",
    "generate_measurement_signal",
    "interpolate_channel_calibration",
    "generate_semi_analog_thd_sweep",
    "grid_smooth",
    "list_devices",
    "log_chirp",
    "log_smooth",
    "log_window",
    "magnitude_db",
    "normalize_peak",
    "peak_levels",
    "phase_derivative",
    "wrap_phase",
    "phase_degrees",
    "periodic_pink_noise",
    "pink_noise",
    "pinking_sos",
    "play_and_record",
    "power_db",
    "require_valid_reference_calibration",
    "speaker_impedance",
    "smooth_power_spectrum",
    "thd_from_spectrum",
    "trim_recording",
    "white_noise",
]
